=head1 Perl::Gib::App

Perl::Gib application. Parse, validate command line options and execute
action.

 use Perl::Gib::App;
 
 my $app = Perl::Gib::App->new();
 $app->run('doc');

=head1 Attributes

=head2 C<has 'action'; #27>

Action to execute, required.

=head2 C<has 'options'; #33>

Perl::Gib configuration options.

=head1 Methods

=head2 C<sub help($self); #74>

Return help message.

=head2 C<sub man($self); #93>

Return manpage.

=head2 C<sub usage($self); #111>

Return usage message.

=head2 C<sub version($self); #129>

Return Perl::Gib version string.

=head2 C<sub run($self, $action); #136>

Run Perl::Gib application.

=cut

#Pod::HTML2Pod conversion notes:
# 809 bytes of input
#Mon Sep  6 18:20:37 2021 tschaefer
# No a_name switch not specified, so will not try to render <a name='...'>
# Will try to render <a href='...'>
