=head1 Perl::Gib::App::CLI

Perl::Gib command line application. Parse, validate command line
options and execute action.

 use Perl::Gib::App::CLI;
 
 exit Perl::Gib::App::CLI->run();

=head2 Inheritance

 Perl::Gib::App::CLI
   isa Perl::Gib:App

=head1 Modifiers

=head2 C<around 'run'; #205>

Run Perl::Gib command line application. Option (configuration) and
action arguments are used from command line.

=cut

#Pod::HTML2Pod conversion notes:
# 488 bytes of input
#Mon Sep  6 18:20:37 2021 tschaefer
# No a_name switch not specified, so will not try to render <a name='...'>
# Will try to render <a href='...'>
